version: '3.5'

services:
  functions:
    build: .
    container_name: functions
    volumes:
      - ./:/app
      - ./.config:/root/.config
    expose:
      - 9229
      - 9228
    ports:
      - 8080:8080
      - 9229:9229 # -> functions inspect helloWorld, not works
      - 9228:9228 # -> node --inspect-brk=0.0.0.0:9228
    command: yarn --cwd functions start
    working_dir: /app
    
